name: flaky_tests
on:
  workflow_dispatch:
  push:

jobs:
  confirm_flaky:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Idoft Fork
        uses: actions/checkout@v5
        
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          cache: maven  
      - name: Clone Repository
        run: |
          git clone https://github.com/kiegroup/jbpm
          cd jbpm
          git rev-parse HEAD

      - name: Run without Tests
        run: |
          cd jbpm
          mvn clean install -DskipTests -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am -Denforcer.skip=true

      - name: Run Tests
        run: |
          cd jbpm
          mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test -Dtest=org.jbpm.casemgmt.impl.CaseIdGeneratorTest#testStartEmptyCaseWithOverridingSequence | tee regular-test.log

      - name: Run NonDex Test
        run: |
          cd jbpm
          mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=jbpm.casemgmt.impl.CaseIdGeneratorTest#testStartEmptyCaseWithOverridingSequence | tee nondex-test.log
    
    
